=== ayeshash0aib/XML/index3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="employes">
    <xs:complexType>
        <xs:sequence>
<xs:element name="employe" maxOccurs="unbounded">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="id" type="xs:integer" />
            <xs:element name="depart" type="xs:string" />
            <xs:element name="courses">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="course1" type="xs:string" />
            <xs:element name="course2" type="xs:string" />
        </xs:sequence>
    </xs:complexType>
</xs:element>
    </xs:sequence>
    </xs:complexType>
</xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== ayeshash0aib/XML/index3.xml
<?xml version="1.0" encoding="UTF-8"?>

<employes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="index3.xsd">

<employe>
    <name> ali</name>
    <id>01</id>
    <depart>accounts</depart>
    <courses>
       <course1>cpism</course1>
       <course2>dism</course2>
    </courses>
</employe>

<employe>
    <name>hamza </name>
    <id>02</id>
    <depart>admin</depart>
    <courses>
        <course1>cpism</course1>
        <course2>dism</course2>
     </courses>
</employe>

<employe>
    <name>maryam </name>
    <id>03</id>
    <depart>sales</depart>
    <courses>
        <course1>cpism</course1>
        <course2>dism</course2>
     </courses>
</employe>

<employe>
    <name>jack </name>
    <id>04</id>
    <depart>sales</depart>
    <courses>
        <course1>cpism</course1>
        <course2>dism</course2>
     </courses>
</employe>

</employes>
